language: php
php:
- 7.0
- 7.1
cache:
  directories:
  - "$HOME/.composer/cache"
env:
- SLIM_VERSION="3.8.*"
- SLIM_VERSION="3.7.*"
- SLIM_VERSION="3.6.*"
- SLIM_VERSION="3.5.*"
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- phpenv config-rm xdebug.ini
install:
- composer install
- composer require slim/slim:${SLIM_VERSION}
script:
- php vendor/bin/phpunit
- "./vendor/bin/phpcs"
after_success:
- php sami.phar update phpdoc.php
addons:
  artifacts:
    debug: true
    s3_region: us-east-1
    target_paths: "$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH"
    paths:
    - "./docs/php"
notifications:
  slack:
    rooms:
      secure: mV51mlAVF1Ilq2K/Z2Pl8M1gfmW1eska38Y0MpqgaJV938BeBUjdDt/ckyqPtHK6w4dw35xEYR1ImjqBNTcBGEIGvAn5HDsLYCpmF7PjDCqFIxNn6d/nxGbUgydefogqYFq9DMo6W7dRzpBS6XuGFR7f3x/rSCUeNysw9DR5qI2NR3WHKFNN7XF1r/Sgr3JX1gnP1Kb7MKz9aN95wGUE+kTzSPlIBfGv5SrmAPgBsqaIZ0LsiqdhFoBADBFFF3Bvk8mNGnlPhW3hTYtFnfGWHzVCly9/QDWh5PJtHsAQXt2oW3tR9DrIKJpgon2xIc+PbA7uWxrhAu78B20dXHiTqH0rltvTNDiYiMZi2hCkQj04jMlVLZQVVr0NhChLFbEtf0rM1lrs3+psUBLFO0kmrzaX8e6cbIQOgh4jh772LPsCNYE5by7qU/RWFr10+sAggSwAERq+0bJPp5huoMynXfNuqr07HPynD3lFmP3RbgIKEWpF3nPZQFvkVSYNW8O0xH6NjoB6eyOQVyfQKrJOiNK+wxE0en0H6I+w/0L/QoopMStrLs2j1cPj26I3EbkhYt964bkSEYf3vJfA9kb884/9Lk2kR3e3HzIAkOMpClhTli/yqEfEovxNKQqt0awS8LrI5Z9PUbQ05uoRa/BsZcNpX7NEQ+U84K6jOT7/eZI=
  on_success: change
  on_failure: always